# Front 서비스는 다른 서비스와 달리 여러 서비스의 yml 을 import 하는 방식을 사용한다.
# 그런데 spring 의 config. import 는 선언된 순서대로 현재 설정을 override 하는 방식이다.
# 따라서 마지막에 import 된 yml 이 모든 설정을 덮어 쓰는 문제가 있다.
# 이 문제를 해결하기 위해 다른 설정에서도 사용하고 있는 속성값은 override 에 따로 정의하고, override yml 파일을 맨 마지막에 import 하는 방식을 사용한다.

spring:
  cloud:
    compatibility-verifier:
      enabled: false
  application:
    name: "backend-api"
  messages:
    basename: messages/**/messages #원래 spring 에서는 message sources 를 이렇게 작성하지 않지만, antMatcher를 사용할 수 있도록 커스터마이징 했으므로 /**/ 패턴을 사용할 수 있다.
  servlet:
    multipart:
      enabled: true
  artemis:
    #mode: EMBEDDED
    embedded:
      enabled: true
      queue-prefix: backend
    pool:
      enabled: true
      max-connections: 50
    provider:
      log-entity: true
      retry-count: 5
      retry-interval: 1000

platform:
  config:
    provider:
      search: QUERY
      mongo: false
      cache:
        type: redis
        evict-on-startup: true
      elastic: none
    asset:
      view:
        domain: http://localhost:8310 #마이크로서비스 모드에서 asset 서버가 다를 경우 해당 서버의 접속 주소를 기입한다. 모놀리틱 서비스인 경우에는 현재 서비스의 대표 주소를 쓰면 된다.

management:
  endpoints:
    web:
      exposure:
        include: "*"
