spring:
  cassandra:
    connection:
      connect-timeout: 10s
      init-query-timeout: 10s
    request:
      timeout: 10s
    pool:
      idle-timeout: 10s
    schema-action: create_if_not_exists
    keyspace-name:
    local-datacenter: DC1
    port: 9042
    contact-points:
    username:
    password:
  data:
    mongodb:
      uri:
      database:
      auto-index-creation: true

logging:
  level:
    com:
      datastax:
        oss:
          driver:
            internal:
              core:
                pool:
                  ChannelPool: Error
